branch-defaults:
  default:
    environment: LP2-Dev
    group_suffix: null
environment-defaults:
  LP-Dev:
    branch: null
    repository: null
global:
  application_name: LuvPenny
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
