export const Assets = {
	"icons": {
		"add_user": require('../assets/icons/add user.png'),
		"archivement": require('../assets/icons/archivement.png'),
		"at": require('../assets/icons/at.png'),
		"bag": require('../assets/icons/bag.png'),
		"bar_chart": require('../assets/icons/bar chart.png'),
		"bell": require('../assets/icons/bell.png'),
		"book": require('../assets/icons/book.png'),
		"bookmark": require('../assets/icons/bookmark.png'),
		"box": require('../assets/icons/box.png'),
		"brush": require('../assets/icons/brush.png'),
		"bulb": require('../assets/icons/bulb.png'),
		"calculator": require('../assets/icons/calculator.png'),
		"calendar": require('../assets/icons/calendar.png'),
		"camcorder": require('../assets/icons/camcorder.png'),
		"camera": require('../assets/icons/camera.png'),
		"checkmark": require('../assets/icons/checkmark.png'),
		"chemistry": require('../assets/icons/chemistry.png'),
		"clip": require('../assets/icons/clip.png'),
		"clock": require('../assets/icons/clock.png'),
		"cloud": require('../assets/icons/cloud.png'),
		"compass": require('../assets/icons/compass.png'),
		"compose": require('../assets/icons/compose.png'),
		"credit_card": require('../assets/icons/credit card.png'),
		"cursor": require('../assets/icons/cursor.png'),
		"dashboard": require('../assets/icons/dashboard.png'),
		"database": require('../assets/icons/database.png'),
		"display": require('../assets/icons/display.png'),
		"download": require('../assets/icons/download.png'),
		"envelope": require('../assets/icons/envelope.png'),
		"file": require('../assets/icons/file.png'),
		"folder": require('../assets/icons/folder.png'),
		"gift": require('../assets/icons/gift.png'),
		"graph": require('../assets/icons/graph.png'),
		"heart": require('../assets/icons/heart.png'),
		"home": require('../assets/icons/home.png'),
		"invisible": require('../assets/icons/invisible.png'),
		"iPad": require('../assets/icons/iPad.png'),
		"iPhone": require('../assets/icons/iPhone.png'),
		"joystick": require('../assets/icons/joystick.png'),
		"key": require('../assets/icons/key.png'),
		"life_belt": require('../assets/icons/life belt.png'),
		"lightning": require('../assets/icons/lightning.png'),
		"like": require('../assets/icons/like.png'),
		"link": require('../assets/icons/link.png'),
		"MacBook": require('../assets/icons/MacBook.png'),
		"magnifying_glass": require('../assets/icons/magnifying glass.png'),
		"map": require('../assets/icons/map.png'),
		"megaphone": require('../assets/icons/megaphone.png'),
		"message": require('../assets/icons/message.png'),
		"microphone": require('../assets/icons/microphone.png'),
		"money": require('../assets/icons/money.png'),
		"movie_file": require('../assets/icons/movie file.png'),
		"package": require('../assets/icons/package.png'),
		"pen": require('../assets/icons/pen.png'),
		"pencil_and_ruler": require('../assets/icons/pencil and ruler.png'),
		"pencil": require('../assets/icons/pencil.png'),
		"picture_file": require('../assets/icons/picture file.png'),
		"piggybank": require('../assets/icons/piggybank.png'),
		"pin": require('../assets/icons/pin.png'),
		"printer": require('../assets/icons/printer.png'),
		"quote": require('../assets/icons/quote.png'),
		"rack": require('../assets/icons/rack.png'),
		"share": require('../assets/icons/share.png'),
		"shield": require('../assets/icons/shield.png'),
		"sight": require('../assets/icons/sight.png'),
		"site_map": require('../assets/icons/site map.png'),
		"sound": require('../assets/icons/sound.png'),
		"spanner": require('../assets/icons/spanner.png'),
		"star": require('../assets/icons/star.png'),
		"stoper": require('../assets/icons/stoper.png'),
		"suitcase": require('../assets/icons/suitcase.png'),
		"tack": require('../assets/icons/tack.png'),
		"tag": require('../assets/icons/tag.png'),
		"telephone": require('../assets/icons/telephone.png'),
		"text_file": require('../assets/icons/text file.png'),
		"transport": require('../assets/icons/transport.png'),
		"trash": require('../assets/icons/trash.png'),
		"trolley": require('../assets/icons/trolley.png'),
		"visible": require('../assets/icons/visible.png'),
		"wallet": require('../assets/icons/wallet.png'),
		"window": require('../assets/icons/window.png'),
		"world": require('../assets/icons/world.png')
	}
};